### ISSUE TITLE
Нефизичный расчет

### ISSUE THREAD

**Issue by resetius** [scientific-tribunal/kvgrav#1]
https://github.com/scientific-tribunal/kvgrav/blob/bda25ea1b4bd156450a61856d5c71ad33fba65f3/src/KVGrav.ts#L130

Здесь расчет не по Ньютону делается. 
scalar * vectorX - фактически проекция силы на ось X. По Ньютону координаты считаются из определения скорости: dr/dt = v, поэтому приближенно можно положить newX = x + vx * dt, а вот v в свою очередь считается уже с помощью силы.

https://github.com/scientific-tribunal/kvgrav/blob/bda25ea1b4bd156450a61856d5c71ad33fba65f3/src/KVGrav.ts#L51

Здесь почему на массу делим? Должно быть произведение масс.

https://github.com/scientific-tribunal/kvgrav/blob/bda25ea1b4bd156450a61856d5c71ad33fba65f3/src/KVGrav.ts#L216

Это тоже не по Ньютону. Надо сначала посчитать общую силу с помощью суммирования, потом обновить ускорение, скорость, координаты. Считать смещения по отдельность, а потом брать среднее это непойми что такое.

https://github.com/scientific-tribunal/kvgrav/blob/bda25ea1b4bd156450a61856d5c71ad33fba65f3/src/KVGrav.ts#L177

Почему здесь берется только ближайшая точка, хотя надо считать для всех?

**Comment by counters** [comment]
1. Я проверял на миллиметровке, формула верная и всё сходилось. Движения в эмуляции пока нет. Об этом написано в о проекте и тут.
2. Если сделать произведение масс, то объект большей массы будет отталкиваться так-же как и меньший. Данная формула позволяет большему объекты сильнее оттолкнуть меньший и наоборот.
3. Читайте 1 пункт.
4. Если просчитать для всех теоритических точек внешнего поля, то получится тоже самое, так-как они друг друга компенсируют и в итоге остаётся та самая заветная точка ближайшая к дизбалансу сил.

Прошу писать отдельными ишью, так-как некоторые вопросы можно уже закрыть, а к примеру по 2му можно подисскутировать.

**Comment by resetius** [comment]
Я дискутировать не собираюсь, я лишь указываю на ошибки. Правильная формула F=GmM/r^2, это подтверждается наблюдениями, а не "миллиметровкой". Из вашей формулы с m/M даже ускорение свободного падения получить не получится. Если движения нет, то зачем меняются координаты, причему методом от балды? Что такое "точка внешнего поля" я даже спрашивать не буду, все равно объяснить не сможете. А если же вы хотите рассмотреть объемлющую сферу, то при учете всех её точек получится ноль, это строгий математический факт и в программе должно быть аналогично, если ноль не получился, то ищите ошибку в программе.

**Comment by counters** [comment]
> Я дискутировать не собираюсь, я лишь указываю на ошибки. Правильная формула F=GmM/r^2, это подтверждается наблюдениями...

Это та самая формула которая работает только с минусом, но вы его по понятной причине не указали. Всё с Вами ясно)
Не собираетесь в таком случае разговор окончен.
